export enum PlannedSavingStatus {
  PENDING = 'pending',
  SKIPPED = 'skipped',
  COMPLETED = 'completed',
}

export interface PlannedSaving {
  id: string;
  amount: number;
  date: Date;
  status: PlannedSavingStatus;
  completedAt?: Date | null;
  accountId?: string;
  budgetId: string;
  plannedIncomeId?: string;
  savingGoalId?: string;
  isAutoGenerated?: boolean;
  account?: { id: string; name: string };
  savingGoal?: { id: string; name: string; reason: string };
  plannedIncome?: { id: string; amount: number; date: Date; source: string };
}
