import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

import { AccountEntity } from '@/modules/api/modules/accounts/infrastructure/database/account.entity';
import { BudgetEntity } from '@/modules/api/modules/budgets/infrastructure/database/entities/budget.entity';
import { PlannedIncomeEntity } from '@/modules/api/modules/incomes/infrstructure/database/entities/incomes-planned.entity';

import { PlannedSavingStatus } from '../../../domain/savings-planned';
import { SavingGoalEntity } from './saving-goals.entity';

@Entity('planned_savings')
export class PlannedSavingEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'budget_id', type: 'uuid', nullable: false })
  budgetId: string;

  @ManyToOne(() => BudgetEntity)
  @JoinColumn({ name: 'budget_id' })
  budget: BudgetEntity;

  @Column({ name: 'planned_income_id', type: 'uuid', nullable: true })
  plannedIncomeId?: string;

  @ManyToOne(() => PlannedIncomeEntity, { nullable: true })
  @JoinColumn({ name: 'planned_income_id' })
  plannedIncome?: PlannedIncomeEntity;

  @Column({ name: 'saving_goal_id', type: 'uuid', nullable: true })
  savingGoalId?: string;

  @ManyToOne(() => SavingGoalEntity, { nullable: true })
  @JoinColumn({ name: 'saving_goal_id' })
  savingGoal?: SavingGoalEntity;

  @Column({ name: 'account_id', type: 'uuid', nullable: true })
  accountId?: string;

  @ManyToOne(() => AccountEntity, { nullable: true })
  @JoinColumn({ name: 'account_id' })
  account?: AccountEntity;

  @Column({
    type: 'decimal',
    precision: 12,
    scale: 2,
  })
  amount: number;

  @Column({
    type: 'enum',
    enum: PlannedSavingStatus,
    default: PlannedSavingStatus.PENDING,
  })
  status: PlannedSavingStatus;

  @Column({ name: 'is_auto_generated', default: true })
  isAutoGenerated: boolean;

  @Column({ type: 'date' })
  date: Date;

  @Column({ name: 'completed_at', type: 'timestamptz', nullable: true })
  completedAt: Date | null;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;
}
