import {
  Column,
  CreateDateColumn,
  Entity,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

import { AccountEntity } from '@/modules/api/modules/accounts/infrastructure/database/account.entity';
import { BudgetEntity } from '@/modules/api/modules/budgets/infrastructure/database/entities/budget.entity';
import { PlannedIncomeEntity } from '@/modules/api/modules/incomes/infrstructure/database/entities/incomes-planned.entity';

import { PlannedSavingStatus } from '../../../domain/savings-planned';
import { SavingGoalEntity } from './saving-goals.entity';

@Entity('planned_savings')
export class PlannedSavingEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ManyToOne(() => BudgetEntity)
  budget: BudgetEntity;

  // 🔥 clave para trazabilidad por ingreso
  @ManyToOne(() => PlannedIncomeEntity)
  plannedIncome: PlannedIncomeEntity;

  @ManyToOne(() => SavingGoalEntity)
  savingGoal: SavingGoalEntity;

  // 👉 redundante pero útil (evita joins)
  @ManyToOne(() => AccountEntity)
  account: AccountEntity;

  @Column({
    type: 'decimal',
    precision: 12,
    scale: 2,
  })
  amount: number;

  @Column({
    type: 'enum',
    enum: PlannedSavingStatus,
    default: PlannedSavingStatus.PENDING,
  })
  status: PlannedSavingStatus;

  // 💡 opcional pero muy útil
  @Column({ default: true })
  isAutoGenerated: boolean;

  // 💡 para control temporal
  @Column({ type: 'date' })
  date: Date;

  @Column({ name: 'completed_at', type: 'timestamptz', nullable: true })
  completedAt: Date | null;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;
}
