import { PlannedSavingStatus } from '../../../domain/savings-planned';
import { PlannedSavingEntity } from '../../database/entities/saving-planned.entity';
import { PlannedSavingMapper } from '../planned.mapper';

const makeEntity = (overrides: Partial<PlannedSavingEntity> = {}): PlannedSavingEntity => {
  const e = new PlannedSavingEntity();
  e.id = 'ps-1';
  e.amount = '25000' as unknown as number;
  e.date = new Date('2024-06-15');
  e.status = PlannedSavingStatus.PENDING;
  e.completedAt = null;
  e.isAutoGenerated = true;
  (e as unknown as Record<string, unknown>).account = undefined;
  (e as unknown as Record<string, unknown>).budget = undefined;
  (e as unknown as Record<string, unknown>).plannedIncome = undefined;
  (e as unknown as Record<string, unknown>).savingGoal = undefined;
  return Object.assign(e, overrides);
};

describe('PlannedSavingMapper', () => {
  describe('toDomain', () => {
    it('maps scalar fields correctly', () => {
      const domain = PlannedSavingMapper.toDomain(makeEntity());

      expect(domain.id).toBe('ps-1');
      expect(domain.amount).toBe(25000);
      expect(domain.date).toEqual(new Date('2024-06-15'));
      expect(domain.status).toBe(PlannedSavingStatus.PENDING);
      expect(domain.completedAt).toBeNull();
    });

    it('converts amount DB string to number', () => {
      const domain = PlannedSavingMapper.toDomain(
        makeEntity({ amount: '99999.99' as unknown as number }),
      );
      expect(typeof domain.amount).toBe('number');
      expect(domain.amount).toBe(99999.99);
    });

    it('maps account relation when present', () => {
      const entity = makeEntity({ account: { id: 'acc-1', name: 'Bancolombia' } as never });
      const domain = PlannedSavingMapper.toDomain(entity);
      expect(domain.accountId).toBe('acc-1');
      expect(domain.account).toEqual({ id: 'acc-1', name: 'Bancolombia' });
    });

    it('sets accountId and account to undefined when not present', () => {
      const domain = PlannedSavingMapper.toDomain(makeEntity({ account: undefined }));
      expect(domain.accountId).toBeUndefined();
      expect(domain.account).toBeUndefined();
    });

    it('maps budget relation when present', () => {
      const entity = makeEntity({ budget: { id: 'budget-1' } as never });
      const domain = PlannedSavingMapper.toDomain(entity);
      expect(domain.budgetId).toBe('budget-1');
    });

    it('maps savingGoal relation when present', () => {
      const entity = makeEntity({
        savingGoal: { id: 'goal-1', name: 'Vacaciones', reason: 'Viaje' } as never,
      });
      const domain = PlannedSavingMapper.toDomain(entity);
      expect(domain.savingGoalId).toBe('goal-1');
      expect(domain.savingGoal).toEqual({ id: 'goal-1', name: 'Vacaciones', reason: 'Viaje' });
    });

    it('sets savingGoal to undefined when not present', () => {
      const domain = PlannedSavingMapper.toDomain(makeEntity({ savingGoal: undefined }));
      expect(domain.savingGoal).toBeUndefined();
    });

    it('maps plannedIncome relation when present', () => {
      const entity = makeEntity({
        plannedIncome: {
          id: 'pi-1',
          amount: '100000',
          date: new Date('2024-06-01'),
          source: 'Salario',
        } as never,
      });
      const domain = PlannedSavingMapper.toDomain(entity);
      expect(domain.plannedIncomeId).toBe('pi-1');
      expect(domain.plannedIncome!.amount).toBe(100000);
      expect(domain.plannedIncome!.source).toBe('Salario');
    });

    it('sets plannedIncome to undefined when not present', () => {
      const domain = PlannedSavingMapper.toDomain(makeEntity({ plannedIncome: undefined }));
      expect(domain.plannedIncome).toBeUndefined();
    });
  });

  describe('toEntity', () => {
    const baseDomain = {
      amount: 25000,
      date: new Date('2024-06-15'),
      status: PlannedSavingStatus.PENDING,
    };

    it('maps required fields onto entity', () => {
      const entity = PlannedSavingMapper.toEntity(baseDomain);
      expect(entity).toBeInstanceOf(PlannedSavingEntity);
      expect(entity.amount).toBe(25000);
      expect(entity.status).toBe(PlannedSavingStatus.PENDING);
    });

    it('does not set id when not provided', () => {
      expect(PlannedSavingMapper.toEntity(baseDomain).id).toBeUndefined();
    });

    it('sets id when provided (for updates)', () => {
      expect(PlannedSavingMapper.toEntity({ id: 'ps-99', ...baseDomain }).id).toBe('ps-99');
    });

    it('creates proxy account entity when accountId provided', () => {
      const entity = PlannedSavingMapper.toEntity({ ...baseDomain, accountId: 'acc-1' });
      expect(entity.account?.id).toBe('acc-1');
    });

    it('creates proxy budget entity when budgetId provided', () => {
      const entity = PlannedSavingMapper.toEntity({ ...baseDomain, budgetId: 'budget-1' });
      expect(entity.budget?.id).toBe('budget-1');
    });

    it('creates proxy plannedIncome entity when plannedIncomeId provided', () => {
      const entity = PlannedSavingMapper.toEntity({ ...baseDomain, plannedIncomeId: 'pi-1' });
      expect(entity.plannedIncome?.id).toBe('pi-1');
    });

    it('creates proxy savingGoal entity when savingGoalId provided', () => {
      const entity = PlannedSavingMapper.toEntity({ ...baseDomain, savingGoalId: 'goal-1' });
      expect(entity.savingGoal?.id).toBe('goal-1');
    });

    it('sets completedAt when provided', () => {
      const date = new Date('2024-06-20');
      const entity = PlannedSavingMapper.toEntity({ ...baseDomain, completedAt: date });
      expect(entity.completedAt).toEqual(date);
    });

    it('sets isAutoGenerated when provided', () => {
      const entity = PlannedSavingMapper.toEntity({ ...baseDomain, isAutoGenerated: false });
      expect(entity.isAutoGenerated).toBe(false);
    });
  });
});
