import {
  BadRequestException,
  ForbiddenException,
  Inject,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { DataSource } from 'typeorm';

import { LoggerProviderService } from '@/core/providers';
import { AccountRepository } from '@/modules/api/modules/accounts/domain/repositories/account.respository';
import { BudgetRepository } from '@/modules/api/modules/budgets/domain/repositories/budget.repository';
import { CategoryType } from '@/modules/api/modules/categories/domain/category';
import { CategoryRepository } from '@/modules/api/modules/categories/domain/repositories/category.repository';
import { PlannedIncomeEntity } from '@/modules/api/modules/incomes/infrstructure/database/entities/incomes-planned.entity';
import { TransactionEntity } from '@/modules/api/modules/transactions/infrastructure/database/entities/transaction.entity';

import { SavingAllocationRepository } from '../../domain/repositories/allocation.repository';
import { GoalHistoryRepository } from '../../domain/repositories/goal-history.repository';
import { GoalsRepository } from '../../domain/repositories/goals.repository';
import { PlannedSavingRepository } from '../../domain/repositories/planned.repository';
import { GoalStatus } from '../../domain/savings-goals';
import { PlannedSaving, PlannedSavingStatus } from '../../domain/savings-planned';
import { SavingGoalEntity } from '../../infrastructure/database/entities/saving-goals.entity';
import { PlannedSavingEntity } from '../../infrastructure/database/entities/saving-planned.entity';
import { CreatePlannedSavingDto } from '../../infrastructure/dto/create-planned-saving.dto';

@Injectable()
export class PlannedSavingService {
  private readonly context: string = PlannedSavingService.name;

  constructor(
    @Inject('PlannedSavingRepository')
    private readonly plannedSavingRepository: PlannedSavingRepository,
    @Inject('GoalsRepository') private readonly goalsRepository: GoalsRepository,
    @Inject('GoalHistoryRepository')
    private readonly goalHistoryRepository: GoalHistoryRepository,
    @Inject('BudgetRepository') private readonly budgetRepository: BudgetRepository,
    @Inject('CategoryRepository') private readonly categoryRepository: CategoryRepository,
    @Inject('AccountRepository') private readonly accountRepository: AccountRepository,
    @Inject('SavingAllocationRepository')
    private readonly allocationRepository: SavingAllocationRepository,
    private readonly dataSource: DataSource,
    private readonly logger: LoggerProviderService,
  ) {}

  async findByBudget(budgetId: string, userId: string): Promise<PlannedSaving[]> {
    const budget = await this.budgetRepository.findById(budgetId);
    if (!budget || budget.ownerId !== userId) {
      throw new NotFoundException('Budget not found');
    }

    return await this.plannedSavingRepository.findByBudget(budgetId);
  }

  async create(userId: string, dto: CreatePlannedSavingDto): Promise<PlannedSaving[]> {
    const budget = await this.budgetRepository.findById(dto.budgetId);
    if (!budget) throw new NotFoundException('Budget not found');
    if (budget.ownerId !== userId) throw new ForbiddenException('Budget not found');
    if (budget.status !== 'ACTIVE') throw new BadRequestException('Budget is not active');

    let savingDate = new Date();
    if (dto.plannedIncomeId) {
      const income = await this.dataSource
        .getRepository(PlannedIncomeEntity)
        .findOne({ where: { id: dto.plannedIncomeId, budgetId: dto.budgetId } });
      if (!income) throw new NotFoundException('Planned income not found in this budget');
      savingDate = income.date;
    }

    // Goal explicitly provided: create single saving linked to that goal
    if (dto.savingGoalId) {
      const goal = await this.goalsRepository.findByIdAndUser(dto.savingGoalId, userId);
      if (!goal) throw new NotFoundException('Saving goal not found');
      if (!goal.accountId) throw new BadRequestException('Goal has no account assigned');

      const saved = await this.plannedSavingRepository.save({
        amount: dto.amount,
        budgetId: dto.budgetId,
        plannedIncomeId: dto.plannedIncomeId,
        savingGoalId: dto.savingGoalId,
        accountId: goal.accountId,
        status: PlannedSavingStatus.PENDING,
        date: savingDate,
        isAutoGenerated: !dto.plannedIncomeId,
      });

      return [saved];
    }

    // No goal: distribute using budget allocations (same logic as markAsReceive)
    const allocations = await this.allocationRepository.find(dto.budgetId);
    const validAllocations = allocations.filter((a) => a.goal?.accountId);

    if (!validAllocations.length) {
      // No allocations configured: create single unlinked saving as fallback
      const saved = await this.plannedSavingRepository.save({
        amount: dto.amount,
        budgetId: dto.budgetId,
        plannedIncomeId: dto.plannedIncomeId,
        status: PlannedSavingStatus.PENDING,
        date: savingDate,
        isAutoGenerated: true,
      });
      return [saved];
    }

    const savingsToCreate = validAllocations.map((a) => ({
      amount: Number((dto.amount * (a.percentage / 100)).toFixed(2)),
      budgetId: dto.budgetId,
      plannedIncomeId: dto.plannedIncomeId,
      savingGoalId: a.goalId,
      accountId: a.goal!.accountId,
      status: PlannedSavingStatus.PENDING,
      date: savingDate,
      isAutoGenerated: true,
    }));

    return await this.plannedSavingRepository.saveMany(savingsToCreate);
  }

  async assignGoal(id: string, savingGoalId: string, userId: string): Promise<PlannedSaving> {
    const saving = await this.plannedSavingRepository.findById(id);
    if (!saving) throw new NotFoundException('Ahorro planificado no encontrado');
    if (saving.status !== PlannedSavingStatus.PENDING) {
      throw new BadRequestException('Solo se puede asignar una meta a ahorros pendientes');
    }

    const budget = await this.budgetRepository.findById(saving.budgetId);
    if (!budget || budget.ownerId !== userId) {
      throw new NotFoundException('Ahorro planificado no encontrado');
    }

    const goal = await this.goalsRepository.findByIdAndUser(savingGoalId, userId);
    if (!goal) throw new NotFoundException('Meta de ahorro no encontrada');
    if (!goal.accountId) throw new BadRequestException('La meta no tiene cuenta asignada');

    const updated = await this.plannedSavingRepository.update(id, {
      savingGoalId,
      accountId: goal.accountId,
    });

    if (!updated) throw new NotFoundException('No se pudo actualizar el ahorro planificado');

    this.logger.info(this.context, `Meta ${savingGoalId} asignada al ahorro planificado ${id}`);
    return updated;
  }

  async markAsDone(
    id: string,
    userId: string,
  ): Promise<{
    savingPlanned: PlannedSaving;
    interestTransaction: TransactionEntity | null;
  }> {
    // Pre-fetch — reads, outside transaction
    const savingPlanned = await this.plannedSavingRepository.findById(id);
    if (!savingPlanned) throw new NotFoundException('Planned Savings not found');
    if (savingPlanned.status === PlannedSavingStatus.COMPLETED) {
      throw new BadRequestException('Este ahorro ya fue ejecutado');
    }

    const budget = await this.budgetRepository.findById(savingPlanned.budgetId);
    if (!budget) throw new NotFoundException('Budget not found');
    if (budget.ownerId !== userId) throw new NotFoundException('Planned Savings not found');

    const category = await this.categoryRepository.findByType(CategoryType.SAVINGS);
    if (!category) throw new NotFoundException('Categoría de ahorro no encontrada');

    const goal = savingPlanned.savingGoalId
      ? await this.goalsRepository.findById(savingPlanned.savingGoalId)
      : null;
    const primaryAccount = await this.accountRepository.findPrimaryByUserId(
      budget.ownerId as string,
    );

    // Calculate interest if goal has a linked account with interestRate > 0
    let interestAmount = 0;
    const today = new Date();

    if (goal) {
      const account = await this.accountRepository.findByIdAndUser(
        goal.accountId,
        goal.userId as string,
      );
      const annualRate = Number(account?.interestRate ?? 0);

      if (annualRate > 0) {
        const completedSavings = await this.plannedSavingRepository.findByGoalId(
          savingPlanned.savingGoalId!,
        );
        const accumulatedAmount = completedSavings
          .filter((s) => s.status === PlannedSavingStatus.COMPLETED)
          .reduce((sum, s) => sum + Number(s.amount), 0);

        if (accumulatedAmount > 0) {
          const periodStart = goal.lastInterestDate ?? goal.createdAt ?? today;
          const days = Math.floor(
            (today.getTime() - new Date(periodStart).getTime()) / (1000 * 60 * 60 * 24),
          );
          if (days > 0) {
            interestAmount = this.calculateInterest(accumulatedAmount, annualRate, days);
          }
        }
      }
    }

    // Atomic section: saving update + savings tx + optional interest tx + date update
    const result = await this.dataSource.transaction(async (manager) => {
      await manager.update(
        PlannedSavingEntity,
        { id },
        {
          status: PlannedSavingStatus.COMPLETED,
          completedAt: today,
        },
      );

      await manager.save(TransactionEntity, {
        amount: savingPlanned.amount,
        type: 'savings' as const,
        source: goal?.name ?? 'Ahorro',
        userId: budget.ownerId,
        budgetId: savingPlanned.budgetId,
        categoryId: category.id,
        accountId: savingPlanned.accountId,
        fromAccountId: primaryAccount?.id,
        toAccountId: savingPlanned.accountId,
        transactionDate: today,
        savingGoalId: savingPlanned.savingGoalId ?? undefined,
        plannedSavingId: savingPlanned.id,
      });

      let interestTx: TransactionEntity | null = null;
      if (interestAmount > 0 && goal) {
        this.logger.info(
          this.context,
          `Creating interest transaction for goal ${goal.id}: ${interestAmount.toFixed(2)}`,
        );
        interestTx = await manager.save(TransactionEntity, {
          amount: Number(interestAmount.toFixed(2)),
          type: 'interest' as const,
          source: `Interés: ${goal.name}`,
          userId: budget.ownerId,
          budgetId: savingPlanned.budgetId,
          categoryId: category.id,
          accountId: savingPlanned.accountId,
          toAccountId: savingPlanned.accountId,
          transactionDate: today,
          savingGoalId: goal.id,
        });
        await manager.update(SavingGoalEntity, { id: goal.id }, { lastInterestDate: today });
      }

      return interestTx;
    });

    // Secondary: goal status SCHEDULED → IN_PROGRESS (non-critical)
    if (goal && goal.status === GoalStatus.SCHEDULED) {
      await this.goalsRepository.update(savingPlanned.savingGoalId!, goal.userId as string, {
        status: GoalStatus.IN_PROGRESS,
      });
      await this.goalHistoryRepository.add({
        goalId: savingPlanned.savingGoalId!,
        userId: goal.userId as string,
        field: 'status',
        oldValue: GoalStatus.SCHEDULED,
        newValue: GoalStatus.IN_PROGRESS,
      });
    }

    const updated = await this.plannedSavingRepository.findById(id);
    return { savingPlanned: updated!, interestTransaction: result };
  }

  private calculateInterest(accumulatedAmount: number, annualRate: number, days: number): number {
    const wholeDays = Math.floor(days);
    return accumulatedAmount * (Math.pow(1 + annualRate / 100, wholeDays / 365) - 1);
  }
}
